spring:
  application:
    name: technical-assessment

  datasource:
    url: jdbc:postgresql://localhost:5432/technical-assessment-inovasi-daya-solusi
    username: postgres
    password: A.sdfghjkl12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
